src/Entity/User/User.php
<?php

namespace App\Entity\User;

use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\File;



/**
 * @ORM\Entity
 * @Vich\Uploadable
 * @ORM\Table(name="user")
 */
class User extends BaseUser
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    public function __construct()
    {
        parent::__construct();
    }

    /**
     * @var string $firstName
     *
     * @ORM\Column(type="string",length=255)
     *
     * @Assert\NotBlank()
     */
    private $firstName ;

    /**
     * @var string $lastName
     *
     * @ORM\Column(type="string",length=255)
     *
     * @Assert\NotBlank()
     */
    private $lastName ;

    /**
     * @var string $street
     *
     * @ORM\Column(type="string",length=255)
     *
     * @Assert\NotBlank()
     */
    private $street ;

    /**
     * @var integer $houseNumber
     *
     * @ORM\Column(type="integer")
     *
     * @Assert\NotBlank()
     */
    private $houseNumber ;

    /**
     * @var integer $plz
     *
     * @ORM\Column(type="integer")
     *
     * @Assert\NotBlank()
     */
    private $plz ;

    /**
     * @var string $city
     *
     * @ORM\Column(type="string",length=255)
     * @Assert\NotBlank()
     *
     */
    private $city ;

    /**
     * @var string $phoneNumber
     *
     * @ORM\Column(type="string")
     *
     * @Assert\NotBlank()
     */
    private $phoneNumber ;

    /**
     * @var string
     *
     * @ORM\Column(type="string")
     *
     * @Assert\NotBlank()
     */
    private $gender;

    /**
     *
     * @ORM\Column(type="date")
     *
     * @Assert\NotBlank()
     *
     */
    private $birthDay;

    /**
     * @var string
     * @ORM\Column(type="string",nullable=true)
     *
     *
     */
    private $accountOwner;

    /**
     * @var string
     *@ORM\Column(type="string",nullable=true)
     *
     *
     */
    private $bankName;

    /**
     * @var string
     * @ORM\Column(type="string",nullable=true)
     *
     */
    private $iban;

    /**
     * @var string
     * @ORM\Column(type="string",nullable=true)
     *
     */
    private $bic;

    /**
     * @ORM\Column(type="string", length=255,nullable=true)
     * @var string
     */
    private $image;

    /**
     * @Vich\UploadableField(mapping="profile_images", fileNameProperty="image")
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="datetime",nullable=true)
     * @var \DateTime
     */
    private $updatedAt;

    /**
     * @var boolean
     * @ORM\Column(type="boolean",nullable=true)
     */
    private $isTeacher;

    /**
     * @var array
     * @ORM\Column(type="array",nullable=true)
     */
    private $certificates;
    /**
     * @var array
     * @ORM\Column(type="array",nullable=true)
     */
    private $syllabus;

    /**
     * @var string
     * @ORM\Column(type="string",nullable=true)
     * @Assert\Url()
     */
    private $facebook;

    /**
     * @var string
     * @ORM\Column(type="string",nullable=true)
     * @Assert\Url()
     */
    private $twitter;

    /**
     * @var string
     * @ORM\Column(type="string",nullable=true)
     * @Assert\Url()
     */
    private $linkedIn;

    /**
     * @return string
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * @param string $city
     * @return User
     */
    public function setCity( $city)
    {
        $this->city = $city;
        return $this;
    }

    /**
     * @return string
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * @param string $firstName
     * @return User
     */
    public function setFirstName( $firstName)
    {
        $this->firstName = $firstName;
        return $this;
    }

    /**
     * @return string
     */
    public function getLastName()
    {
        return $this->lastName;
    }

    /**
     * @param string $lastName
     * @return User
     */
    public function setLastName( $lastName)
    {
        $this->lastName = $lastName;
        return $this;
    }

    /**
     * @return string
     */
    public function getStreet()
    {
        return $this->street;
    }

    /**
     * @param string $street
     * @return User
     */
    public function setStreet( $street)
    {
        $this->street = $street;
        return $this;
    }

    /**
     * @return int
     */
    public function getHouseNumber()
    {
        return $this->houseNumber;
    }

    /**
     * @param int $houseNumber
     * @return User
     */
    public function setHouseNumber( $houseNumber)
    {
        $this->houseNumber = $houseNumber;
        return $this;
    }

    /**
     * @return int
     */
    public function getPlz()
    {
        return $this->plz;
    }

    /**
     * @param int $plz
     * @return User
     */
    public function setPlz($plz)
    {
        $this->plz = $plz;
        return $this;
    }

    /**
     * @return int
     */
    public function getPhoneNumber()
    {
        return $this->phoneNumber;
    }

    /**
     * @param int $phoneNumber
     * @return User
     */
    public function setPhoneNumber( $phoneNumber)
    {
        $this->phoneNumber = $phoneNumber;
        return $this;
    }


    /**
     * @return string
     */
    public function getGender()
    {
        return $this->gender;
    }

    /**
     * @param string $gender
     * @return User
     */
    public function setGender($gender)
    {
        $this->gender = $gender;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getBirthDay()
    {
        return $this->birthDay;
    }

    /**
     * @param \DateTime $birthDay
     * @return User
     */
    public function setBirthDay( $birthDay)
    {
        $this->birthDay = $birthDay;
        return $this;
    }


    /**
     * @return string
     */
    public function getAccountOwner()
    {
        return $this->accountOwner;
    }

    /**
     * @param string $accountOwner
     * @return User
     */
    public function setAccountOwner( $accountOwner)
    {
        $this->accountOwner = $accountOwner;
        return $this;
    }

    /**
     * @return string
     */
    public function getBankName()
    {
        return $this->bankName;
    }

    /**
     * @param string $bankName
     * @return User
     */
    public function setBankName( $bankName)
    {
        $this->bankName = $bankName;
        return $this;
    }

    /**
     * @return string
     */
    public function getBic()
    {
        return $this->bic;
    }

    /**
     * @param string $bic
     * @return User
     */
    public function setBic( $bic)
    {
        $this->bic = $bic;
        return $this;
    }

    /**
     * @return string
     */
    public function getIban()
    {
        return $this->iban;
    }

    /**
     * @param string $iban
     * @return User
     */
    public function setIban( $iban)
    {
        $this->iban = $iban;
        return $this;
    }

    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;

        // VERY IMPORTANT:
        // It is required that at least one field changes if you are using Doctrine,
        // otherwise the event listeners won't be called and the file is lost
        if ($image) {
            // if 'updatedAt' is not defined in your entity, use another property
            $this->updatedAt = new \DateTime('now');
        }
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function setImage($image)
    {
        $this->image = $image;
    }

    public function getImage()
    {
        return $this->image;
    }

    /**
     * @return \DateTime
     */
    public function getUpdatedAt():? \DateTime
    {
        return $this->updatedAt;
    }

    /**
     * @return bool
     */
    public function isTeacher():? bool
    {
        return $this->isTeacher;
    }

    /**
     * @param bool $isTeacher
     * @return User
     */
    public function setIsTeacher(bool $isTeacher):? User
    {
        $this->isTeacher = $isTeacher;
        return $this;
    }

    /**
     * @return array
     */
    public function getCertificates():? array
    {
        return $this->certificates;
    }

    /**
     * @param array $certificates
     * @return User
     */
    public function setCertificates(array $certificates): User
    {
        $this->certificates = $certificates;
        return $this;
    }

    /**
     * @return string
     */
    public function getFacebook():? string
    {
        return $this->facebook;
    }

    /**
     * @param string $facebook
     * @return User
     */
    public function setFacebook(string $facebook): User
    {
        $this->facebook = $facebook;
        return $this;
    }

    /**
     * @return string
     */
    public function getTwitter():? string
    {
        return $this->twitter;
    }

    /**
     * @param string $twitter
     * @return User
     */
    public function setTwitter(string $twitter): User
    {
        $this->twitter = $twitter;
        return $this;
    }

    /**
     * @return string
     */
    public function getLinkedIn():? string
    {
        return $this->linkedIn;
    }

    /**
     * @param string $linkedIn
     * @return User
     */
    public function setLinkedIn(string $linkedIn): User
    {
        $this->linkedIn = $linkedIn;
        return $this;
    }

    /**
     * @return array
     */
    public function getSyllabus():? array
    {
        return $this->syllabus;
    }

    /**
     * @param array $syllabus
     * @return User
     */
    public function setSyllabus(array $syllabus): User
    {
        $this->syllabus = $syllabus;
        return $this;
    }

src/Controller/CoursesController.php
<?php

namespace App\Controller;


use App\Entity\Course\Course;
use App\Entity\Course\UserCourses;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class CoursesController extends Controller
{
    /**
     * @Route("/courses",name="courses_index")
     * @Template("courses/index.html.twig")
     *
     * @return array
     */
     public function index()
     {
         return [
             'courses' => $this->getDoctrine()->getRepository(Course::class)->findBy(['status'=>Course::ACTIVE]),
         ];
     }

    /**
     * @Route("/course/show/{id}",name="course_show")
     * @Template("courses/show.html.twig")
     *
     * @param Course $course
     * @return array
     */
     public function show(Course $course)
     {
         return [
             'courseStudents'=>$this->getDoctrine()->getRepository(UserCourses::class)->findBy(['course'=>$course]),
             'course'=>$course
         ];
     }
}

templates/courses/index.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="about_bg">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1>{{ 'app.courses'|trans }}</h1>
                </div>
            </div>
        </div>
    </div>
<!--============================= Course list =============================-->
<div class="notice">
    <div class="container">
        <div class="row">
            {% for course in courses  %}
            <div class="col-md-12">
                <div class="event_date">
                    <div class="event-date-wrap">
                        {#<p>{{ course.startsAt|date('h') }}</p>#}
                        <span>{{ course.startsAt|date('M') }}.{{ course.startsAt|date('d') }}</span>
                    </div>
                </div>
                <div class="date-description">
                    <h3><a href="{{ path('course_show',{'id':course.id}) }}">{{ course.title }}</a></h3>
                    <p>{{ course.description }}</p>
                    <hr class="event_line">
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

<!--//End Course list -->
{% endblock %}

templates/courses/registration.email.html.twig
<p>Dear {{ user.firstName }} {{ user.lastName }},</p>
<p></p>
<p>Thank you for registering to {{ course.title }}. Your registration received.</p>
<p></p>
<p>One more step to go then you will be ready to learn with us.</p>
<p>In the attachment you will find the contract.</p>
<p>Kindly we need your signature that you agree to go further with the course registration process and send it back to us as soon as possible</p>
<p></p>
<p>Kind Regards,</p>
<p>Lawrence Shalaan</p>
<p>Metzinger Str. 5/1,</p>
<p>73230 Kirchheim</p>
<p>+4917624086095</p>

templates/courses/show.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<div class="about_bg">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>{{ 'course.details'|trans }}</h1>
            </div>
        </div>
    </div>
</div>
    <!--============================= ADMISSION DETAILS COURCES =============================-->
    <section class="admission_cources">
        <div class="container">
            <div class="row text-center">
                <div class="col-md-12">
                    <h2>{{ course.title }}</h2>
                </div>
            </div>
            <div class="row justify-content-md-center">
                <div class="col-lg-6">
                    <div class="admission_discription">
                        <h4>{{ course.title }}</h4>
                        <!-- // end .star-rating -->
                        <p>{{ course.description }}</p>
                    </div>
                    <div class="admission-pdf">
                        {#<i class="fa fa-file-pdf-o fa-3x" aria-hidden="true"></i>#}
                        {#<p>course details PDF#}
                            {#<br>#}
                            {#<a href="#">DOWNLOAD</a>#}
                        {#</p>#}

                        {% if app.user.hasAllRequiredFieldsFoRegisteration == true   %}
                            <a href="#" data-toggle="modal" data-target="#exampleModalCenter" class="btn btn-warning btn-pdf_join">{{ 'course.joining'|trans }}</a>
                        {% else %}
                            <p> {{ 'app.pfrofile.not.completed'|trans }} <a href="{{ path('user_bank_data') }}">{{ 'app.here'|trans }}</a></p>
                        {% endif %}
                    </div>
                </div>
                <div class="col-lg-4">
                    <ul class="admission_rating">
                        <li class="admission_star-second">{{ 'course.starts'|trans }}<span>:</span></li>
                        <li class="admission_star">{{ course.startsAt|date('d.M.Y') }}</li>
                        <li>Duration<span>:</span></li>
                        {#todo : to change it #}
                        <li class="admission_star">
                            {% set difference = date(course.endsAt).diff(date(course.startsAt)) %}
                            {% set leftDays = difference.days %}
                            {% if leftDays == 1 %}
                                1 day
                            {% else %}
                                {{ leftDays }} days
                            {% endif %}</li>
                        <li class="admission_star-second">{{ 'course.timing'|trans }}<span>:</span></li>
                        <li class="admission_star">{{ course.startingHour|date('H:i') }} - {{ course.finishingHour|date('H:i') }}</li>
                        <li>{{ 'course.fees'|trans }}<span>:</span></li>
                        <li class="admission_star">{{ course.cost }} €</li>
                        <li>{{ 'course.seates'|trans }}<span>:</span></li>
                        <li class="admission_star">{{ course.seats }}</li>
                        <li>{{ 'course.occupied.seats'|trans }}<span>:</span></li>
                        <li class="admission_star">{{ course.bookedSeats }}</li>
                        <li>{{ 'app.certificateFees'|trans }}<span>:</span></li>
                        <li class="admission_star">{{ course.certificateFees }} ({{ 'app.optional'|trans }})</li>
                        <li>{{ 'app.status'|trans }}<span>:</span></li>
                        {% set courseStatus =  'course.'~course.status %}
                        <li class="admission_star">{{ courseStatus |trans }}</li>
                    </ul>
                    <div class="admission_insruction">
                        <h4>{{ 'course.Instructor'|trans }}</h4>
                        {% if course.teacher.image is not null %}
                        <img src="{{ asset('uploads/images/profile/'~course.teacher.image) }}" class="img-fluid" alt="#">
                        {% else %}
                            <img src="{{asset("uploads/images/profile/download.jpeg")}}" class="img-fluid about-img" alt="#">
                        {% endif %}
                        <p>{{ course.teacher.firstName }} {{ course.teacher.lastName }}
                            <br>
                            <span>{% for syllabu in  course.teacher.syllabus  %} {{ syllabu }} {% endfor %}</span></p>
                    </div>
                    {#<div class="admission_share-icon">#}
                        {#<h4>Share Course</h4>#}
                        {#<a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>#}
                        {#<a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>#}
                        {#<a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a>#}
                        {#<a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a>#}
                    {#</div>#}
                </div>
            </div>
        </div>
    </section>
    <!--//END ADMISSION DETAILS COURCES -->

    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">{{ 'app.registeration.apply'|trans }}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                <p>
                    {{ 'course.registration.modal.message'|trans  }}
                </p>
                <form  action="{{ path('course_register',{'courseId':course.id}) }}" method="post">

                        <input type="checkbox" name="certificate" value="true"> {{ 'form.with.certificate'|trans }}</input>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">{{ 'course.apply'|trans }}</button>
                </div>
                </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}